CREATE TABLE `MEMBRO_TB` (
  `ID_MEMBRO`    int(11)      NOT NULL AUTO_INCREMENT,
  `NOME`         varchar(100) NOT NULL,
  `FK_ID_PESSOA` int(11),
  
  PRIMARY KEY (`ID_MEMBRO`)
  
  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;