CREATE TABLE `LOCALIDADE_TB` (
  `ID_LOCALIDADE`    int(11)     NOT NULL,
  `FK_ID_UF`         int(11)     NOT NULL,
  `CEP`              varchar(8)  NOT NULL,
  `DESCRICAO`        varchar(50) NOT NULL,
  
  
  PRIMARY KEY (`ID_LOCALIDADE`),
  LOCALIDADE_IDX1 INDEX (`CEP`),
  
  FOREIGN KEY (`FK_ID_UF`) REFERENCES UF_TB(`ID_UF`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;