CREATE TABLE `ENDERECO_TB` (
  `ID_ENDERECO`           int(11)     NOT NULL AUTO_INCREMENT,
  `FK_ID_TIPO_LOGRADOURO` int(11)     NOT NULL,
  `LOGRADOURO`            varchar(80) NOT NULL,
  `NUMERO`                varchar(10),
  `COMPLEMENTO`           varchar(20),
  `CEP`                   varchar(8)  NOT NULL,
  `BAIRRO`                varchar(30) NOT NULL,
  `FK_ID_LOCALIDADE`      int(11)     NOT NULL,
  `FK_ID_UF`              int(11)     NOT NULL,
  `FK_ID_PESSOA`          int(11)     NOT NULL,

  
  
  PRIMARY KEY (`ID_ENDERECO`),
  
  FOREIGN KEY (`FK_ID_UF`)              REFERENCES UF_TB(`ID_UF`)
  FOREIGN KEY (`FK_ID_TIPO_LOGRADOURO`) REFERENCES TIPO_LOGRADOURO_TB(`ID_TIPO_LOGRADOURO`)
  FOREIGN KEY (`FK_ID_LOCALIDADE`)      REFERENCES LOCALIDADE_TB(`ID_LOCALIDADE`),
  FOREIGN KEY (`FK_ID_UF`)              REFERENCES UF_TB(`ID_UF`),
  FOREIGN KEY (`FK_ID_PESSOA`)          REFERENCES PESSOA_TB(`ID_PESSOA`)

  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;