CREATE TABLE `BAIRRO_TB` (
  `ID_BAIRRO`        int(11)     NOT NULL,
  `FK_ID_UF`         int(11)     NOT NULL,
  `FK_ID_LOCALIDADE` int(11)     NOT NULL,
  `CEPINICIAL`       varchar(8)  NOT NULL,
  `CEPFINAL`         varchar(8)  NOT NULL,
  `DESCRICAO`        varchar(50) NOT NULL,
  
  
  PRIMARY KEY (`ID_BAIRRO`),
  
  FOREIGN KEY (`FK_ID_UF`)         REFERENCES UF_TB(`ID_UF`)
  FOREIGN KEY (`FK_ID_LOCALIDADE`) REFERENCES LOCALIDADE_TB(`ID_LOCALIDADE`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;