CREATE TABLE `TIPO_LOGRADOURO_TB` (
  `ID_TIPO_LOGRADOURO` int(11)     NOT NULL,
  `DESCRICAO`          varchar(30) NOT NULL,
  `ABREVIATURA`        varchar(10) NOT NULL,
  
  PRIMARY KEY (`ID_TIPO_LOGRADOURO`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;