CREATE TABLE `AREA_ATUACAO_TB` (
  `ID_AREA_ATUACAO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100)  NOT NULL,
  PRIMARY KEY (`ID_AREA_ATUACAO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
